export const STYLE_GUIDE =
  'https://drive.google.com/file/d/115WX4Tu6I519J699XrmOmLclVQMxRt6B/view'
export const SITE_MAP =
  'https://drive.google.com/file/d/1J62bz-DA33XEYrpRrUKJx-s2ZpqZ2Q0p/view'
export const GOOGLE_DOCS = 'https://www.google.com/docs/about/'
export const GOOGLE_SITES = 'http://sites.google.com/'
export const GATSBY = 'https://www.gatsbyjs.com/'
export const GATSBY_CREATIVE =
  'https://www.gatsbyjs.org/starters/JohnJKerr/gatsby-creative/'
export const REACT = 'https://reactjs.org/'
export const LIGHTHOUSE = 'https://developers.google.com/web/tools/lighthouse'
export const FONT_AWESOME_FREE = 'https://github.com/FortAwesome/Font-Awesome'
export const PIXABAY = 'https://pixabay.com/'
export const CANVA = 'https://www.canva.com/'
export const GITHUB = 'https://github.com/'
export const VERCEL = 'https://vercel.com/'
export const VS_CODE = 'https://code.visualstudio.com/'
export const IMOVIE = 'https://www.apple.com/imovie/'
export const GIMP = 'https://www.gimp.org/'
export const WEBEX = 'https://www.webex.com/'
export const ZOOM = 'https://zoom.us/'
export const PHOTO_BOOTH =
  'https://support.apple.com/guide/photo-booth/welcome/mac'
export const YOUTUBE = 'http://youtube.com/'
export const ARTICULAR_RISE = 'https://articulate.com/360/rise'
export const BLACKBOARD_COURSESITES = 'https://www.coursesites.com/'
export const PIKTOCHART = 'https://piktochart.com/'
export const PADLET = 'https://padlet.com/'
export const FLIPGRID = 'https://info.flipgrid.com/'
export const TRELLO = 'https://trello.com/en-US'
export const SLACK = 'https://slack.com/'
